@startuml
left to right direction
' Application Service
class "<<Application>>\nBookingCampGroundService" as BookingCampGroundService {}

' Users Resources
class "<<Resource>>\nUsers" as ResourceUsers {
    <<POST>> +register()
    <<POST>> +login()
    <<GET>> +getme()
    <<POST>> +logout()
}

class "<<Representation>>\nUser" as RepresentationUser {
    - name: String
    - email: String
    - telephone: String
    - role: String <<enum>> {user, admin}
    - createdAt: Date
}

note right of RepresentationUser
 User can only view/edit/delete own Appointments
 Admin can view/edit/delete every Appoin
end note

' Appointments Resources
class "<<Resource>>\nAppointments" as ResourceAppointments {
    <<GET>> +getAllAppointments()
    <<POST>> +createAppointment()
}

class "<<Resource>>\nAppointment" as ResourceAppointment {
    <<GET>> +getOneAppointment()
    <<PUT>> +updateAppointment()
    <<DELETE>> +deleteAppointment()
}

class "<<Representation>>\nAppointment" as RepresentationAppointment {
    - apptDate: Date
    - user: User
    - campground: Campground
    - createdAt: Date
}

' Campgrounds Resources
class "<<Resource>>\nCampgrounds" as ResourceCampgrounds {
    <<GET>> +getAllCampgrounds()
    <<POST>> +createCampground()
}

class "<<Resource>>\nCampground" as ResourceCampground {
    <<GET>> +getOneCampground()
    <<PUT>> +updateCampground()
    <<DELETE>> +deleteCampground()
}

class "<<Representation>>\nCampground" as RepresentationCampground {
    - name: String
    - address: String
    - district: String
    - province: String
    - postalcode: String
    - telephone: String
}

' Resource path relationships
BookingCampGroundService ..> ResourceUsers : "/auth\n<<Path>>"
ResourceUsers ..>  RepresentationUser : "<<use>>"

BookingCampGroundService ..> ResourceAppointments : "/appointments\n<<Path>>"
ResourceAppointments ..> ResourceAppointment : "/:id\n<<Path>>"
ResourceAppointment ..> RepresentationAppointment : "<<use>>"

BookingCampGroundService ..> ResourceCampgrounds : "/campgrounds\n<<Path>>"
ResourceCampgrounds ..> ResourceCampground : "/:id\n<<Path>>"
ResourceCampground ..> RepresentationCampground : "<<use>>"

' Relationships between representations (models)
RepresentationUser "1" -- "0..3" RepresentationAppointment : "books up to 3"
RepresentationAppointment "1" -- "1" RepresentationCampground : "belongs to"
RepresentationCampground "1" -- "0..*" RepresentationAppointment : "has many"

@enduml
